## Lesson 7. Data analysis

1. Numpy
2. Pandas
3. Project: Titanic

### 1. Numpy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

NumPy's main object is the homogeneous multidimensional array.

NumPy’s array class is called __ndarray__. 

In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

#### Array Creation

1.from python list

In [134]:
b = np.array([4, 5, 6])

In [135]:
b

array([4, 5, 6])

In [11]:
type(b)

numpy.ndarray

In [136]:
c = np.array([1.2, 3.5, 5.1])

In [137]:
c.dtype

dtype('float64')

In [138]:
c.itemsize

8

In [139]:
d = np.array([1, 2, 3], dtype=np.complex128)

In [140]:
d

array([ 1.+0.j,  2.+0.j,  3.+0.j])

In [141]:
d.dtype, d.itemsize

(dtype('complex128'), 16)

In [18]:
e = np.array([(1.5, 2, 3), (4, 5, 6)])

In [19]:
e

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

2.sequence array (arange)

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

3.create arrays with initial placeholder content

In [21]:
np.zeros([3, 4])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [22]:
np.ones([2, 3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [143]:
# Identity Matrix
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [144]:
np.eye(3,4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [24]:
np.empty((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [145]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [146]:
np.arange(10, 30, 3.5)

array([ 10. ,  13.5,  17. ,  20.5,  24. ,  27.5])

In [147]:
np.linspace(0, 2, 9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [148]:
np.pi

3.141592653589793

In [149]:
np.linspace(0, 2*np.pi, 100)

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

#### Basic Operations

1.Matrix operation

In [150]:
a = np.array([20, 30, 40, 50])

In [151]:
b = np.arange(4)

In [152]:
a + b

array([20, 31, 42, 53])

In [153]:
a + 100

array([120, 130, 140, 150])

In [154]:
m = [2, 3]
n = [100, 200]

In [155]:
m + n

[2, 3, 100, 200]

In [156]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 1], [0, 1]])

In [157]:
A

array([[1, 1],
       [0, 1]])

In [158]:
B

array([[2, 1],
       [0, 1]])

In [159]:
A*B

array([[2, 1],
       [0, 1]])

In [160]:
A.dot(B)

array([[2, 2],
       [0, 1]])

In [39]:
B.dot(A)

array([[2, 3],
       [0, 1]])

In [40]:
np.dot(A, B)

array([[2, 2],
       [0, 1]])

In [163]:
a = np.random.random((2,3))

In [161]:
np.random.random?

In [164]:
print a

[[ 0.74813228  0.72203416  0.44796532]
 [ 0.12404626  0.74976264  0.86736783]]


In [165]:
a.T

array([[ 0.74813228,  0.12404626],
       [ 0.72203416,  0.74976264],
       [ 0.44796532,  0.86736783]])

2.shape operator

In [166]:
print a

[[ 0.74813228  0.72203416  0.44796532]
 [ 0.12404626  0.74976264  0.86736783]]


In [167]:
a.flatten()

array([ 0.74813228,  0.72203416,  0.44796532,  0.12404626,  0.74976264,
        0.86736783])

In [168]:
a.ravel()

array([ 0.74813228,  0.72203416,  0.44796532,  0.12404626,  0.74976264,
        0.86736783])

In [169]:
b = a.flatten('F')
print b

[ 0.74813228  0.12404626  0.72203416  0.74976264  0.44796532  0.86736783]


In [170]:
b = b.reshape([2,3])

In [171]:
b


array([[ 0.74813228,  0.12404626,  0.72203416],
       [ 0.74976264,  0.44796532,  0.86736783]])

3.aggregation operator:min, max,mean, std

In [172]:
b.min(), b.max(), b.mean(), b.std()

(0.12404626252309092,
 0.86736782629626397,
 0.60988474832042627,
 0.25159827979417998)

In [173]:
b.sum()

3.6593084899225579

In [174]:
b

array([[ 0.74813228,  0.12404626,  0.72203416],
       [ 0.74976264,  0.44796532,  0.86736783]])

In [175]:
b.sum(axis=1)

array([ 1.5942127 ,  2.06509579])

In [176]:
b.sum(axis=0)

array([ 1.49789492,  0.57201158,  1.58940198])

In [177]:
b.argmax()

5

#### Indexing, Slicing and Iterating

In [178]:
a = np.arange(10)**3

In [179]:
print a

[  0   1   8  27  64 125 216 343 512 729]


In [180]:
a[2]

8

In [181]:
a[2:6]

array([  8,  27,  64, 125])

In [182]:
a[:6:2]

array([ 0,  8, 64])

In [61]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [183]:
def f(x,y):
    return 10*x+y

In [184]:
b = np.fromfunction(f, (5,4), dtype=int)

In [185]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [186]:
b[2,3]

23

In [66]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [67]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [68]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

#### Stacking and split

In [69]:
a = np.floor(10*np.random.random((2,2)))

In [70]:
a

array([[ 3.,  2.],
       [ 0.,  4.]])

In [71]:
b = np.floor(10*np.random.random((2,2)))
print b

[[ 0.  4.]
 [ 4.  1.]]


In [72]:
np.vstack((a, b))

array([[ 3.,  2.],
       [ 0.,  4.],
       [ 0.,  4.],
       [ 4.,  1.]])

In [73]:
m = np.hstack((a, b))
m

array([[ 3.,  2.,  0.,  4.],
       [ 0.,  4.,  4.,  1.]])

In [74]:
np.concatenate([a, b],axis=0)

array([[ 3.,  2.],
       [ 0.,  4.],
       [ 0.,  4.],
       [ 4.,  1.]])

In [75]:
np.concatenate([a, b], axis=1)

array([[ 3.,  2.,  0.,  4.],
       [ 0.,  4.,  4.,  1.]])

In [76]:
np.hsplit(m, 2)

[array([[ 3.,  2.],
        [ 0.,  4.]]), array([[ 0.,  4.],
        [ 4.,  1.]])]

In [77]:
np.vsplit(m, 2)

[array([[ 3.,  2.,  0.,  4.]]), array([[ 0.,  4.,  4.,  1.]])]

### 2. Pandas: Panel Data System

Build on top of Numpy

Ideal tool for: cleaning, Analyzing, modeling data

In [ ]:
!pip install pandas

In [78]:
import pandas as pd

#### Series

one-dimension array & dictionary like objects

In [187]:
a = pd.Series(range(4))

In [188]:
print a

0    0
1    1
2    2
3    3
dtype: int64


In [189]:
a.index = ['A', 'B', 'C', 'D']

In [190]:
print a

A    0
B    1
C    2
D    3
dtype: int64


In [191]:
print a[2], a.iloc[2]

2 2


In [192]:
a['A']

0

In [193]:
a.loc['C']

2

In [194]:
a.index = ['A', 2, 'C', 'D']

In [195]:
a

A    0
2    1
C    2
D    3
dtype: int64

In [196]:
a[2]

1

In [197]:
a.iloc[2]

2

In [198]:
a = {'A': 1, 'B': 2, 'C':3}

In [199]:
c = pd.Series(a)

In [200]:
c

A    1
B    2
C    3
dtype: int64

In [201]:
c.ndim

1

In [95]:
c.shape

(3,)

In [96]:
c.index

Index([u'A', u'B', u'C'], dtype='object')

In [97]:
c.values

array([1, 2, 3])

Series Method

In [98]:
c.describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

In [99]:
c.head()

A    1
B    2
C    3
dtype: int64

In [100]:
c.head(2)

A    1
B    2
dtype: int64

In [101]:
c.tail(2)

B    2
C    3
dtype: int64

In [102]:
c.apply(lambda x:x**2 +100)

A    101
B    104
C    109
dtype: int64

In [105]:
map(lambda x:x**2 +100, c)

[101, 104, 109]

In [103]:
c.nunique() # Return number of unique elements in the object.

3

In [104]:
c.unique()

array([1, 2, 3])

#### DataFrame
2-dimensional labeled data structure with columns of potentially different types

1.Create a DataFrame

In [202]:
# From dict of Series or dicts
d = {'one' : pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
     'two' : pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}

In [203]:
df1 = pd.DataFrame(d)
df1

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [204]:
# From dict of ndarrays / lists
df2 = pd.DataFrame({'k1': list('abcd' * 25),
                'k2': list('xy' * 25 + 'yx' * 25),
                'v1': np.random.rand(100),
                'v2': np.random.rand(100)})

In [205]:
df2.head(10)

k1 k2        v1        v2
0  a  x  0.210565  0.323729
1  b  y  0.705538  0.547983
2  c  x  0.329169  0.936569
3  d  y  0.801190  0.007576
4  a  x  0.758187  0.537330
5  b  y  0.211867  0.122178
6  c  x  0.746045  0.440517
7  d  y  0.459219  0.332126
8  a  x  0.449715  0.966935
9  b  y  0.811225  0.371295

In [206]:
# From a list of dicts
data2 = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]
df3 = pd.DataFrame(data2)

In [207]:
df3

a   b     c
0  1   2   NaN
1  5  10  20.0

2.Column selection, addition, deletion

In [112]:
df2.head()

k1 k2        v1        v2
0  a  x  0.647856  0.448537
1  b  y  0.552626  0.709635
2  c  x  0.400633  0.865950
3  d  y  0.904663  0.321224
4  a  x  0.765632  0.521620

In [ ]:
df2.k1

In [113]:
df2['k1']

0     a
1     b
2     c
3     d
4     a
5     b
6     c
7     d
8     a
9     b
10    c
11    d
12    a
13    b
14    c
15    d
16    a
17    b
18    c
19    d
20    a
21    b
22    c
23    d
24    a
25    b
26    c
27    d
28    a
29    b
     ..
70    c
71    d
72    a
73    b
74    c
75    d
76    a
77    b
78    c
79    d
80    a
81    b
82    c
83    d
84    a
85    b
86    c
87    d
88    a
89    b
90    c
91    d
92    a
93    b
94    c
95    d
96    a
97    b
98    c
99    d
Name: k1, dtype: object

In [114]:
df2['v3'] = df2['v2'] * df2['v1']

In [115]:
df2.head()

k1 k2        v1        v2        v3
0  a  x  0.647856  0.448537  0.290587
1  b  y  0.552626  0.709635  0.392163
2  c  x  0.400633  0.865950  0.346928
3  d  y  0.904663  0.321224  0.290600
4  a  x  0.765632  0.521620  0.399369

In [116]:
# Columns can be deleted or popped like with a dict:
del df2['v3']

In [117]:
df2.head()

k1 k2        v1        v2
0  a  x  0.647856  0.448537
1  b  y  0.552626  0.709635
2  c  x  0.400633  0.865950
3  d  y  0.904663  0.321224
4  a  x  0.765632  0.521620

In [118]:
df2.pop('v2')

0     0.448537
1     0.709635
2     0.865950
3     0.321224
4     0.521620
5     0.320487
6     0.601268
7     0.055019
8     0.797296
9     0.019461
10    0.627772
11    0.643415
12    0.860315
13    0.478514
14    0.301271
15    0.051428
16    0.154393
17    0.788446
18    0.451262
19    0.857633
20    0.100374
21    0.488298
22    0.022474
23    0.873408
24    0.630385
25    0.615970
26    0.218299
27    0.351613
28    0.176837
29    0.130671
        ...   
70    0.921132
71    0.143683
72    0.068613
73    0.226554
74    0.914968
75    0.522826
76    0.167670
77    0.966274
78    0.050153
79    0.072739
80    0.898906
81    0.577651
82    0.197093
83    0.412852
84    0.737578
85    0.330890
86    0.196724
87    0.936688
88    0.547766
89    0.498217
90    0.090297
91    0.172462
92    0.137510
93    0.752854
94    0.953121
95    0.145280
96    0.144884
97    0.577387
98    0.539102
99    0.190470
Name: v2, dtype: float64

In [119]:
df2.head()

k1 k2        v1
0  a  x  0.647856
1  b  y  0.552626
2  c  x  0.400633
3  d  y  0.904663
4  a  x  0.765632

In [120]:
# insert
df2['foo'] = 'bar'

In [121]:
df2.head()

k1 k2        v1  foo
0  a  x  0.647856  bar
1  b  y  0.552626  bar
2  c  x  0.400633  bar
3  d  y  0.904663  bar
4  a  x  0.765632  bar

In [122]:
df2.insert(1, 'bar', df2['k1'])

In [123]:
df2.head()

k1 bar k2        v1  foo
0  a   a  x  0.647856  bar
1  b   b  y  0.552626  bar
2  c   c  x  0.400633  bar
3  d   d  y  0.904663  bar
4  a   a  x  0.765632  bar

3.Indexing / Selection

|Operation	|Syntax	|Result|
| ------------- |:-------------:| -----:|
|Select column	|df[col]	|Series
|Select row by label	|df.loc[label]	|Series|
|Select row by integer location	|df.iloc[loc]	|Series
|Slice rows	|df[5:10]	|DataFrame
|Select rows by boolean vector	|df[bool_vec]	|DataFrame

In [124]:
df1

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [125]:
# Select column
df1['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [126]:
# Select row by label
df1.loc['a']

one    1.0
two    1.0
Name: a, dtype: float64

In [127]:
# Select row by integer location
df1.iloc[0]

one    1.0
two    1.0
Name: a, dtype: float64

In [128]:
# Slice rows
df1[2:4]

one  two
c  3.0  3.0
d  NaN  4.0

In [129]:
# Select rows by boolean vector
df1[df1.one > 2]

one  two
c  3.0  3.0

In [130]:
df1

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [131]:
df1['one']['a'] = 100

In [132]:
df1['one'].loc['b'] = 20

4.statistics, aggregating

In [201]:
df4 = pd.DataFrame(np.random.randn(25).reshape(5,5), index=list('abcde'),columns=list('vwxyz'))
df4

v         w         x         y         z
a -1.160455  0.684878  0.500291 -0.004452 -0.053909
b  0.113392  0.715282 -0.825856  0.667326  0.064025
c -0.069384  0.504540  0.616307 -0.547494  0.172195
d -0.213073 -0.262190  0.142630 -1.699384  0.636631
e -0.307482 -1.233599  0.070863  0.292559  0.936806

In [202]:
df4.describe()

v         w         x         y         z
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean  -0.327400  0.081782  0.100847 -0.258289  0.351149
std    0.492016  0.835511  0.567159  0.919922  0.419235
min   -1.160455 -1.233599 -0.825856 -1.699384 -0.053909
25%   -0.307482 -0.262190  0.070863 -0.547494  0.064025
50%   -0.213073  0.504540  0.142630 -0.004452  0.172195
75%   -0.069384  0.684878  0.500291  0.292559  0.636631
max    0.113392  0.715282  0.616307  0.667326  0.936806

In [203]:
# sum
df4.sum(axis=0)

v   -1.637002
w    0.408912
x    0.504235
y   -1.291446
z    1.755747
dtype: float64

In [204]:
df4.sum(axis=1)

a   -0.033647
b    0.734170
c    0.676164
d   -1.395386
e   -0.240854
dtype: float64

In [206]:
df4.min(axis=1)

a   -1.160455
b   -0.825856
c   -0.547494
d   -1.699384
e   -1.233599
dtype: float64

In [207]:
df4.max(axis=0)

v    0.113392
w    0.715282
x    0.616307
y    0.667326
z    0.936806
dtype: float64

5.select, filter, join, group

In [212]:

# Create a toy dataset with 2 categorical and 2 numeric variables
df5 = pd.DataFrame({'k1': list('abcd' * 25),
                'k2': list('xy' * 25 + 'yx' * 25),
                'v1': np.random.rand(100),
                'v2': np.random.rand(100)})
df5.head()

k1 k2        v1        v2
0  a  x  0.725413  0.317406
1  b  y  0.830823  0.374494
2  c  x  0.768971  0.935240
3  d  y  0.762935  0.328745
4  a  x  0.212582  0.202521

In [213]:
# select

df5['k1']

0     a
1     b
2     c
3     d
4     a
5     b
6     c
7     d
8     a
9     b
10    c
11    d
12    a
13    b
14    c
15    d
16    a
17    b
18    c
19    d
20    a
21    b
22    c
23    d
24    a
25    b
26    c
27    d
28    a
29    b
     ..
70    c
71    d
72    a
73    b
74    c
75    d
76    a
77    b
78    c
79    d
80    a
81    b
82    c
83    d
84    a
85    b
86    c
87    d
88    a
89    b
90    c
91    d
92    a
93    b
94    c
95    d
96    a
97    b
98    c
99    d
Name: k1, dtype: object

In [215]:
df5[['k1', 'v2']]

k1        v2
0   a  0.317406
1   b  0.374494
2   c  0.935240
3   d  0.328745
4   a  0.202521
5   b  0.808102
6   c  0.167320
7   d  0.687541
8   a  0.203519
9   b  0.782569
10  c  0.725927
11  d  0.480759
12  a  0.858573
13  b  0.318749
14  c  0.400883
15  d  0.267524
16  a  0.415886
17  b  0.116787
18  c  0.605760
19  d  0.285731
20  a  0.250425
21  b  0.123892
22  c  0.922555
23  d  0.731203
24  a  0.667916
25  b  0.133649
26  c  0.966121
27  d  0.956951
28  a  0.448439
29  b  0.369554
.. ..       ...
70  c  0.937434
71  d  0.640947
72  a  0.344694
73  b  0.861159
74  c  0.823807
75  d  0.559210
76  a  0.411504
77  b  0.082498
78  c  0.872035
79  d  0.799632
80  a  0.064948
81  b  0.992274
82  c  0.168966
83  d  0.980096
84  a  0.766201
85  b  0.402651
86  c  0.118150
87  d  0.825782
88  a  0.752715
89  b  0.117638
90  c  0.106328
91  d  0.880099
92  a  0.733786
93  b  0.009956
94  c  0.274352
95  d  0.520540
96  a  0.133254
97  b  0.838829
98  c  0.268086
99  d  0.938390

[100 rows x 2 columns]

In [219]:
# filter
df5.query("k1 == 'a' and v2 > 0.5")

k1 k2        v1        v2
12  a  x  0.469290  0.858573
24  a  x  0.805556  0.667916
36  a  x  0.092163  0.948378
40  a  x  0.167482  0.957284
44  a  x  0.188901  0.756507
48  a  x  0.696715  0.754881
56  a  y  0.553540  0.778303
60  a  y  0.268100  0.608452
68  a  y  0.611854  0.636759
84  a  y  0.049987  0.766201
88  a  y  0.692753  0.752715
92  a  y  0.298183  0.733786

In [222]:
df5[(df5.k1 == 'a') & (df5.v2 > 0.5)]

k1 k2        v1        v2
12  a  x  0.469290  0.858573
24  a  x  0.805556  0.667916
36  a  x  0.092163  0.948378
40  a  x  0.167482  0.957284
44  a  x  0.188901  0.756507
48  a  x  0.696715  0.754881
56  a  y  0.553540  0.778303
60  a  y  0.268100  0.608452
68  a  y  0.611854  0.636759
84  a  y  0.049987  0.766201
88  a  y  0.692753  0.752715
92  a  y  0.298183  0.733786

In [223]:
df5[(df5['k1'] == 'a') & (df5['v2'] > 0.5)]

k1 k2        v1        v2
12  a  x  0.469290  0.858573
24  a  x  0.805556  0.667916
36  a  x  0.092163  0.948378
40  a  x  0.167482  0.957284
44  a  x  0.188901  0.756507
48  a  x  0.696715  0.754881
56  a  y  0.553540  0.778303
60  a  y  0.268100  0.608452
68  a  y  0.611854  0.636759
84  a  y  0.049987  0.766201
88  a  y  0.692753  0.752715
92  a  y  0.298183  0.733786

In [221]:
df5.query("k1 == 'a' and v2 > v1 and k2 != 'y'")

k1 k2        v1        v2
12  a  x  0.469290  0.858573
16  a  x  0.379371  0.415886
32  a  x  0.213256  0.265375
36  a  x  0.092163  0.948378
40  a  x  0.167482  0.957284
44  a  x  0.188901  0.756507
48  a  x  0.696715  0.754881

In [228]:
df5[(df5.k1 == 'a') & (df5.v2 > df5.v1) & (df5.k2 != 'y')]

k1 k2        v1        v2
12  a  x  0.469290  0.858573
16  a  x  0.379371  0.415886
32  a  x  0.213256  0.265375
36  a  x  0.092163  0.948378
40  a  x  0.167482  0.957284
44  a  x  0.188901  0.756507
48  a  x  0.696715  0.754881

In [208]:
# Join

# Let's define a few toy datasets to use as examples

df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                 'data1': np.random.randn(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                 'data2': np.random.randn(3)})

df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                 'data3': np.random.randn(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
                 'data4': np.random.randn(3)})

In [209]:
df1

data1 key
0  0.034116   b
1 -0.957844   b
2 -1.866200   a
3  0.221667   c
4 -1.325359   a
5 -0.341266   a
6 -0.492518   b

In [210]:
df2

data2 key
0  1.279742   a
1 -2.527137   b
2 -0.462918   d

In [211]:
df3

data3 lkey
0 -1.125174    b
1 -1.593782    b
2  0.515121    a
3 -0.458260    c
4  1.975875    a
5  0.509288    a
6  1.134601    b

In [212]:
df4

data4 rkey
0  0.297238    a
1  1.218185    b
2  1.852437    d

In [241]:
# inner join
# by defult, inner join
pd.merge(df1, df2)

data1 key     data2
0  0.504411   b -2.377747
1  0.812863   b -2.377747
2  0.786575   b -2.377747
3 -0.648827   a -1.311693
4  0.007690   a -1.311693
5  0.045584   a -1.311693

In [242]:
# yield an error, because no matching columns
pd.merge(df1, df4)

MergeError: No common columns to perform merge on

In [243]:
df2.merge(right=df1, how='inner', on='key')

data2 key     data1
0 -1.311693   a -0.648827
1 -1.311693   a  0.007690
2 -1.311693   a  0.045584
3 -2.377747   b  0.504411
4 -2.377747   b  0.812863
5 -2.377747   b  0.786575

In [244]:
df1.merge(right=df2, how='inner', on='key')

data1 key     data2
0  0.504411   b -2.377747
1  0.812863   b -2.377747
2  0.786575   b -2.377747
3 -0.648827   a -1.311693
4  0.007690   a -1.311693
5  0.045584   a -1.311693

In [245]:
# left join
df1.merge(right=df2, how='left', on='key')

data1 key     data2
0  0.504411   b -2.377747
1  0.812863   b -2.377747
2 -0.648827   a -1.311693
3 -0.004980   c       NaN
4  0.007690   a -1.311693
5  0.045584   a -1.311693
6  0.786575   b -2.377747

In [246]:
# right join
df1.merge(right=df2, how='right', on='key')

data1 key     data2
0  0.504411   b -2.377747
1  0.812863   b -2.377747
2  0.786575   b -2.377747
3 -0.648827   a -1.311693
4  0.007690   a -1.311693
5  0.045584   a -1.311693
6       NaN   d  0.019718

In [247]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')
# still an inner join!

data3 lkey     data4 rkey
0  0.573086    b -0.645663    b
1  1.254722    b -0.645663    b
2  2.240799    b -0.645663    b
3 -0.395714    a  1.128098    a
4  0.550145    a  1.128098    a
5  0.790893    a  1.128098    a

#### specify suffixes

In [248]:
# Add a column with the same name to df1 and df2
df1['colx'] = np.random.randn(7)
df2['colx'] = np.random.randn(3)

# Specifying suffixes to identify columns with the same name
pd.merge(df1, df2, on='key', suffixes=['_l', '_r'])

data1 key    colx_l     data2    colx_r
0  0.504411   b  0.543984 -2.377747  0.737976
1  0.812863   b  0.088421 -2.377747  0.737976
2  0.786575   b -1.192280 -2.377747  0.737976
3 -0.648827   a -0.351555 -1.311693  0.744201
4  0.007690   a  0.309544 -1.311693  0.744201
5  0.045584   a  0.181643 -1.311693  0.744201

In [249]:
# concat
pd.concat([df1, df2])


colx     data1     data2 key
0  0.543984  0.504411       NaN   b
1  0.088421  0.812863       NaN   b
2 -0.351555 -0.648827       NaN   a
3  0.975301 -0.004980       NaN   c
4  0.309544  0.007690       NaN   a
5  0.181643  0.045584       NaN   a
6 -1.192280  0.786575       NaN   b
0  0.744201       NaN -1.311693   a
1  0.737976       NaN -2.377747   b
2 -1.275810       NaN  0.019718   d

In [250]:
pd.concat([df1, df2], axis=1)


data1 key      colx     data2  key      colx
0  0.504411   b  0.543984 -1.311693    a  0.744201
1  0.812863   b  0.088421 -2.377747    b  0.737976
2 -0.648827   a -0.351555  0.019718    d -1.275810
3 -0.004980   c  0.975301       NaN  NaN       NaN
4  0.007690   a  0.309544       NaN  NaN       NaN
5  0.045584   a  0.181643       NaN  NaN       NaN
6  0.786575   b -1.192280       NaN  NaN       NaN

In [253]:
pd.concat([df1, df2], axis=1, join = 'inner')

data1 key      colx     data2 key      colx
0  0.504411   b  0.543984 -1.311693   a  0.744201
1  0.812863   b  0.088421 -2.377747   b  0.737976
2 -0.648827   a -0.351555  0.019718   d -1.275810

In [213]:
# group

# Create a toy dataset with 2 categorical and 2 numeric variables
df = pd.DataFrame({'k1': list('abcd' * 25),
                'k2': list('xy' * 25 + 'yx' * 25),
                'v1': np.random.rand(100),
                'v2': np.random.rand(100)})
df.head(10)

k1 k2        v1        v2
0  a  x  0.814811  0.104542
1  b  y  0.599905  0.303040
2  c  x  0.184265  0.559548
3  d  y  0.809557  0.330756
4  a  x  0.700006  0.738879
5  b  y  0.434742  0.419635
6  c  x  0.892965  0.122289
7  d  y  0.720692  0.860307
8  a  x  0.999851  0.363603
9  b  y  0.918152  0.279179

In [256]:
# gropuby one key
df.groupby('k1')

In [257]:
df.groupby('k1').mean()

v1        v2
k1                    
a   0.480743  0.492609
b   0.426254  0.515983
c   0.534815  0.466174
d   0.624885  0.485868

In [258]:
# groupby two keys
df.groupby(['k1','k2']).mean()


v1        v2
k1 k2                    
a  x   0.461676  0.420626
   y   0.501400  0.570591
b  x   0.415669  0.413504
   y   0.436025  0.610579
c  x   0.477476  0.462217
   y   0.587744  0.469827
d  x   0.638828  0.477006
   y   0.609779  0.495467

In [259]:
df.groupby([df['k1'],df['k2']]).sum()

v1        v2
k1 k2                    
a  x   6.001782  5.468132
   y   6.016794  6.847095
b  x   4.988024  4.962051
   y   5.668324  7.937522
c  x   5.729712  5.546604
   y   7.640673  6.107755
d  x   8.304770  6.201084
   y   7.317346  5.945610

In [261]:
#Or you can pass the name of a function as a string with the .agg() method

df.groupby(df['k1']).agg([np.sum, np.mean, np.median, np.max, np.min])

v1                                                 v2            \
          sum      mean    median      amax      amin        sum      mean   
k1                                                                           
a   12.018577  0.480743  0.469250  0.910830  0.139728  12.315227  0.492609   
b   10.656348  0.426254  0.371832  0.999850  0.027018  12.899573  0.515983   
c   13.370385  0.534815  0.540720  0.999082  0.010208  11.654359  0.466174   
d   15.622116  0.624885  0.682295  0.998972  0.000534  12.146694  0.485868   

                                  
      median      amax      amin  
k1                                
a   0.528504  0.894447  0.050926  
b   0.529071  0.940217  0.046888  
c   0.449874  0.942713  0.007821  
d   0.556874  0.940997  0.012324

In [262]:
df[['v1','v2']].groupby(df['k1']).agg({'v1':['min','mean'], 'v2':['max']})

v1                  v2
         min      mean       max
k1                              
a   0.139728  0.480743  0.894447
b   0.027018  0.426254  0.940217
c   0.010208  0.534815  0.942713
d   0.000534  0.624885  0.940997

#### The .apply( ) method

In [270]:
# Retrieve the top N cases fro each group
def topn(data, col, N):
    return data.sort_values(col, ascending=False).loc[:,col].head(N)
d = df.groupby(df['k2']).apply(topn, col=['v1'], N=5)

In [271]:
d

v1
k2             
x  85  0.999850
   59  0.998972
   79  0.936178
   99  0.935607
   2   0.922848
y  54  0.999082
   15  0.996083
   13  0.943236
   29  0.928932
   98  0.853224

#### Reshape Data – pivot() and pivot_table()

In [214]:
# Set up a toy dataframe
df = pd.DataFrame({'date': (list(pd.date_range('2000-01-03', '2000-01-05')) * 4),
               'item': (list('ABCD'*3)),
               'status': (np.random.randn(12))})

In [215]:
df

date item    status
0  2000-01-03    A -1.721948
1  2000-01-04    B  0.717342
2  2000-01-05    C -0.484604
3  2000-01-03    D  1.109304
4  2000-01-04    A  0.787129
5  2000-01-05    B  1.087562
6  2000-01-03    C  1.130717
7  2000-01-04    D -0.620689
8  2000-01-05    A -0.489335
9  2000-01-03    B  1.298247
10 2000-01-04    C -0.706420
11 2000-01-05    D  0.310586

In [276]:
# 1. Using pivot() reshape the data from long to wide
df.pivot(index='date', columns='item', values='status')

item               A         B         C         D
date                                              
2000-01-03  0.603726 -0.605846 -0.367191  1.550000
2000-01-04  0.080075 -1.290359  4.182357 -0.907569
2000-01-05 -0.480551  1.357314  1.778431 -1.779784

pivot_table() is similar to pivot, but can 
  * work with duplicate indices and 
  * lets you specify an aggregation function

In [278]:
df = pd.DataFrame({'C1':list(('x' * 4 + 'y' * 4)*2),
                   'C2':list('abbbaabaabbbaaba'),
                   'N1':np.random.randn(16)})

df

C1 C2        N1
0   x  a -0.014743
1   x  b -0.204264
2   x  b -0.088337
3   x  b  0.365966
4   y  a  0.687456
5   y  a -1.000911
6   y  b  1.381896
7   y  a -1.087309
8   x  a -0.289166
9   x  b  0.172302
10  x  b -0.838106
11  x  b  0.835743
12  y  a -1.093162
13  y  a  1.161541
14  y  b -3.101219
15  y  a -1.864723

In [279]:
df.pivot_table?

In [284]:
df.pivot_table(index='C1', columns='C2', values='N1', aggfunc='mean')

C2         a         b
C1                    
x  -0.151955  0.040551
y  -0.532851 -0.859661

In [285]:
df.pivot(index='C1', columns='C2', values='N1')

ValueError: Index contains duplicate entries, cannot reshape